name: testing

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev
      - name: Testing
        run: pipenv run test
      - name: Coverage
        run: pipenv run python -m pytest --cache-clear --cov=. test
